//from uri in sdm-key
@cmisuri = https://api-sdm-di.cfapps.eu10.hana.ondemand.com

//from uaa/clientid in sdm-key
@cmisclientid = sb-9c868b6c-506a-4063-b792-2f5f2120f715!b114925|sdm-di-SDM_DI_PROD-prod!b41064
//from uaa/clientsecret in sdm-key
@cmisclientsecret = 2bcba531-62ea-4723-82d2-d44aaa4fe4d4$6ikixfVM8M8jHnqelMMNsopTYzVgHoqr6J3faZPJU7c=

//from uaa/url in sdm-key
@cmistokenurl = https://apjcoe-x66183k9.authentication.eu10.hana.ondemand.com


# @name getToken
POST {{cmistokenurl}}/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{cmisclientid}}:{{cmisclientsecret}}

client_id={{cmisclientid}}
&grant_type=client_credentials

###

# @name createRepository
@authToken = {{getToken.response.body.access_token}}
POST {{cmisuri}}/rest/v2/repositories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

	{
		"repository": {
			"displayName": "freightorderattach",
			"description": "freightorderattach",
			"repositoryType": "internal",
			"isVersionEnabled":"false",
			"isVirusScanEnabled":"false",
			"skipVirusScanForLargeFile": "false",
			"isThumbnailEnabled": "false",
			"isEncryptionEnabled": "false",
			"isClientCacheEnabled": "false",
			"hashAlgorithms":"SHA-256",
			"isContentBridgeEnabled" : "false" 
			}
	}



###

# @name getRepository
@authToken = {{getToken.response.body.access_token}}
GET {{cmisuri}}/browser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

# @name delRepository
@authToken = {{getToken.response.body.access_token}}
DELETE  {{cmisuri}}/browser/zfoattachment008 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}











